### ISSUE TITLE
Need Help: PiPass Installed, still get normal 404

### ISSUE THREAD

**Issue by QuarterSwede** [PiPass/blockpage#70] opened 2020-04-20 23:10 UTC
I love the idea of PiPass but can't seem to get it to show the blockpage.

I installed PiPass 1.3 on my HOOBS server with Pi-Hole running alongside. Installation was successful and I filled out the config.php file. However, I still get a normal 404 (using macOS Catalina and Safari) and not the blockpage. I'm testing it on "ads.google.com" that I added to the Pi-Hole blacklist using exact blocking, its definitely getting blocked. Not sure what I must be doing wrong. My config.php file is below.

```
$conf['show_tech_info'] = true;
// Should usually be set to true, unless you have specific reason to disable
// it. Determines whether the program should show technical info.

$conf['blockpage_url'] = "http://192.168.0.11/var/www/html/blockpage/";
// The URL (not directory) of your blockpage. Setting this incorrectly can
// lead to SSL certificate SAN errors, which prompt the user that the
// connection is "not secure." It's highly reccomended that you change this.
// Example: "https://example.com/blockpage/"

$conf['unblock_url'] = "unblock-exec";
// In most cases this does not have to be changed. Only change it if your
// unblock page resides in a subpath which is not "unblock-exec"

$conf['safeurl'] = "about:home";
// Enter a URL of your choice to go to when a user clicks "back to safety"
// This should not be a directory.

$conf['adminemail'] = "myemailaddress@provider.com";
// Your email. Used when a user requests a permanent unblock.

$conf['timezone'] = date_default_timezone_set("America/Denver");
// Your timezone. Used when displaying technical info.

$conf['date'] = date('m/d/Y h:i:s a', time());
// Format in which the date/time is presented to end users.

$conf['unblock_seconds'] = 7200;
// How many seconds to unblock a website for when a temporary unblock is
// executed by a user.

$conf['time_friendly'] = "2 hours";
// A way of saying the amount of unblock seconds in english.
// For example, 300 seconds would equal 5 minutes.

$conf['pipass_v'] = "1.3";
// PiPass current version. Must be a NUMBER! Or else "update available" 
// will be showing forever and you will get a HEADACHE trying to debug.
?>
```

**Comment by roenw** [comment] 2020-04-20 23:49
Change this line:
```$conf['blockpage_url'] = "http://192.168.0.11/var/www/html/blockpage/";```
to this:
```$conf['blockpage_url'] = "http://192.168.0.11/blockpage/";```

**Comment by QuarterSwede** [comment] 2020-04-21 00:56
Thanks for the quick response. I changed it to that, rebooted, but it's still doing the same normal 404 and not the blockpage. Same on my iPhone. The Pi's IP is static.

**Comment by roenw** [comment] 2020-04-21 01:20
Which webserver are you using?

**Comment by QuarterSwede** [comment] 2020-04-21 01:23
That's probably the issue. Nginx is disabled as HOOBS and PiHole both use port 80.

**Comment by QuarterSwede** [comment] 2020-04-21 22:12
So I changed HOOBS to port 88 and enabled Nginx again and the blockpage works on the pi's own IP (accidental discovery on first go after reboot) but NOT on the blacklisted ads.google.com page ...

**Comment by roenw** [comment] 2020-04-22 01:58
On a command line on a regular computer, what is the result of ``curl ads.google.com``? And on the Pi-Hole itself?

It should look something like the following:
```
C:\Users\roenw>curl ads.google.com
<form action="http://10.72.5.5/blockpage" method="get" id="urlpass">
    <input type="hidden" name="url" value="ads.google.com">
</form>
<script>
document.getElementById('urlpass').submit();
</script>
```

**Comment by QuarterSwede** [comment] 2020-04-22 02:02
From the computer:
```
$ curl ads.google.com
<form action="http://192.168.0.11/blockpage/" method="get" id="urlpass">
    <input type="hidden" name="url" value="ads.google.com">
</form>
<script>
document.getElementById('urlpass').submit();
</script>%  
```

From the Pi:
```
hoobs@hoobs:~ $ curl ads.google.com
<form action="http://192.168.0.11/blockpage/" method="get" id="urlpass">
    <input type="hidden" name="url" value="ads.google.com">
</form>
<script>
document.getElementById('urlpass').submit();
```

**Comment by roenw** [comment] 2020-04-22 02:05
When visiting ads.google.com, what behavior exactly do you experience?

**Comment by QuarterSwede** [comment] 2020-04-22 02:06
[Screenshot](https://imgur.com/e5gb6Fa)

**Comment by roenw** [comment] 2020-04-22 02:10
This is expected behavior due to ads.google.com having HSTS enabled. Meaning, your computer has previously connected to ads.google.com and cached a piece of data from Google Ads instructing your computer to refuse a connection if the site (or your Pi-Hole, in this instance) fails to provide a trusted certificate. Unfortunately there is no way around it except either cleaning your cache (since you have successfully visited this site before) or self-signing and trusting a certificate for your Pi-Hole.

**Comment by QuarterSwede** [comment] 2020-04-22 02:14
It looks like it's apart of google.com as it doesn't have separate entry in Safari's cookie/cache manager. And since I have several accounts I really didn't want to flush the cache and have to relogin (2FA for each). I can blacklist another site I suppose and see what happens. That would've been a lot easier come to think of it.

**Comment by roenw** [comment] 2020-04-22 02:15
That's understandable. I don't have a Mac on hand but I believe you can clear HSTS headers by deleting the ``~/Library/Cookies/HSTS.plist`` file.

**Comment by QuarterSwede** [comment] 2020-04-22 02:30
You nailed it. If I had previously viewed the site THEN added it it just resolves a 404. If I block a site before going to it I get the blockpage.

**Comment by roenw** [comment] 2020-04-22 02:42
The 404 error might indicate your webserver is not configured correctly to handle 404 errors. In the event that it encounters a 404, for PiPass, it should redirect to the 'webroot'. So for example, if you went to ``ads.google.com/blah`` on my home network, the Pi would reply with ``301 Moved Permanently`` to ``ads.google.com``, then another ``301`` to ``http://10.72.5.5/blockpage``.

**Comment by QuarterSwede** [comment] 2020-04-22 02:52
Hmm, I’ll look into that. Either way it looks like PiPass is in the clear. Thank you for the great help!

**Comment by roenw** [comment] 2020-05-05 21:24
Seems like your issue is solved! I'm going to go ahead and close it, if you need further asistance, please create a thread on the new [PiPass Discourse](https://forum.pipass.net/).

**Closed as completed by roenw** 2020-05-05 21:24 UTC
Labels: need help
